config/routes.rb
Getlive::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :recruiters do |f|
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "registrations#new"
  end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" } do |f|
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    match "/creating_jobseeker" => "registrations#creating_jobseeker", :as => :creating_jobseeker
  end

  match "/auth/:provider/callback" => "authorizations#create"

  match "/list_of_applied"                        => "job_posts#show_applied_candidate"
  match "/recruiter/home"                         => "home#rec_index", :as => :rec_index
  match "/search/resume"                          => "home#search_resume", :as => :search_resume
  match "/aboutus"                                => "home#about_us", :as => :about_us
  match "/post/job"                               => "job_posts#job_post", :as => :job_post
  match "/candidates/:id"                         => "job_posts#show_applied_candidate"
  match "/edit_job_post/:id"                      => "job_posts#edit_job_post"
  put "/update_job_post"                          => "job_posts#update_job_post"
  delete "/delete_job_post/:id"                   => "job_posts#delete_job_post"
  match   "/profile/:id"                          => "job_posts#show_profile"
  match "update_profile"                            => "job_posts#update_profile"

  resources :job_posts, :only =>[:update], :as    => :recruiter_path

  match "/candidate_details/:type/:id" => 'job_posts#candidate_details'

  match "/create/job" => "job_posts#create_job", :as => :create_job
  match 'my_post' => 'job_posts#my_post'
  match "/jobs" => "job_posts#show_jobs", :as => :show_jobs #posted by recruiters
  match "/all_jobs" => "job_seekers#all_jobs", :as => :all_jobs
  match "/job_detail/:id" => "job_seekers#job_description"
  match "/apply_for_job/:id" => "job_seekers#apply_for_job", :as => :apply_for_job
  match "/upload" => "job_seekers#upload_file"
  match "/apply_without_signup/:id" => "job_seekers#apply_without_signup", :as => :apply_without_signup
  match "/create_unregistered_user" => "job_seekers#create_unregistered_user", :as => :create_user_record
  match "/signup/second_step/:id" => "job_seekers#signup_second_step", :as => :signup_second_step
  match "/creating_user_info" => "job_seekers#creating_user_info", :as => :creating_user_info
  match "/update_states" => "job_seekers#update_states"
  match "/jobseeker/dashboard" => "job_seekers#jobseeker_dashboard", :as => :jobseeker_dashboard

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about_us

  end

  def rec_index
    render :layout => 'recruiter'
  end

  def search_resume
    @users = User.all
    @unregistered = UnregisteredUser.all
    @resumes = @users + @unregistered
    render :layout => 'recruiter'
  end

end

app/views/home/about_us.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<div class="abt_left">
  <%= "AboutUs" %><br /><br />
  <%= link_to "Get Live Solutions","#" %>
</div>

<div class="abt_right" style="float:right;">
  <%= link_to "Ramco Cloud ERP Solutions","#" %><br />
  <%= link_to "Human Resource Staffing Solutions","#" %><br />
  <%= link_to "Software Development","#" %><br />
  <%= link_to "Business Process Outsourcing","#" %>
</div>

app/views/home/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= link_to "Getlive", about_us_path %>

app/views/home/rec_index.html.erb
<%#= link_to "List of Posted Job", my_post_path %>

<%#= link_to "Candidates applied", list_of_applied_path %>
<div class="contentBg">
	<div class="container">
		<div class="content">
			<div class="contentSection">
				<h3>Get Live Dashboard</h3>
				<div class="upArrow"></div>
				<div class="dashboardIcon"></div>
			</div>
			<div class="userBox">
				<div class="userBg"><img src="/assets/user.jpg" />
				</div>
				<div class="userText">
					<p>
						<strong><%= current_recruiter.full_name %></strong>
					</p>
					<p>
						<%= current_recruiter.position_title %>
					</p>
					<p>
						Toronto, ON, Canada
					</p>
					<p>
						Get Live Solutions
					</p>
					<p>
						<a href="mailto:<%= current_recruiter.email %>" title="<%= current_recruiter.email %>"><%= current_recruiter.email %></a>
					</p>
					<ul class="socialIcon">
						<li>
							<a href="#" title="Facebook"><img src="/assets/facebook-icon.png" alt="Facebook" /></a>
						</li>
						<li>
							<%= link_to image_tag('twitter-icon.png'),"#{current_recruiter.twitter_url}", :alt =>"Twitter", :title=>"Twitter", :target=>"_blank" %>
							<!-- <a href="#" title="Twitter"><img src="/assets/twitter-icon.png" alt="Twitter" /></a> -->
						</li>
						<li>
							<%= link_to image_tag('linkedin-icon.png'),"https://#{current_recruiter.linkedin_url}", :alt =>"LinkedIn", :title=>"LinkedIn", :target=>"_blank" %>
							<!-- <a href="#" title="LinkedIn"><img src="/assets/linkedin-icon.png" alt="LinkedIn" /></a> -->
						</li>
					</ul>
				</div>
			</div>
			<div class="boxSection">
				<div class="box">
					<%= link_to image_tag('find-resumes.png'), search_resume_path, :title => "Find Resumes", :alt =>"Find Resumes" %>
					<!-- <a href="#" title="Find Resumes"><img src="/assets/find-resumes.png" alt="Find Resumes" title="Find Resumes" /></a> -->
				</div>
				<div class="box">
					<%= link_to image_tag('help-wanted.png'), job_post_path, :alt=>"Help Wanted", :title=>"Help Wanted" %>
					<!-- <a href="#" title="Help Wanted"><img src="/assets/help-wanted.png" alt="Help Wanted" title="Help Wanted" /></a> -->
				</div>
				<div class="fl">
					<%= link_to image_tag('manage-jobs.png'), my_post_path, :alt=>"Manage Jobs", :title=>"Manage Jobs" %>
					<!-- <a href="#" title="Manage Jobs"><img src="/assets/manage-jobs.png" alt="Manage Jobs" title="Manage Jobs" /></a> -->
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/search_resume.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "search_resume.html" %>
<% @resumes.each do |f| %>
<%= f.email %><br/>
<% end %>