config/routes.rb
Getlive::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :recruiters do |f|
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "registrations#new"
  end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" } do |f|
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    match "/creating_jobseeker" => "registrations#creating_jobseeker", :as => :creating_jobseeker
  end

  match "/auth/:provider/callback" => "authorizations#create"

  match "/list_of_applied"                        => "job_posts#show_applied_candidate"
  match "/recruiter/home"                         => "home#rec_index", :as => :rec_index
  match "/search/resume"                          => "home#search_resume", :as => :search_resume
  match "/aboutus"                                => "home#about_us", :as => :about_us
  match "/post/job"                               => "job_posts#job_post", :as => :job_post
  match "/candidates/:id"                         => "job_posts#show_applied_candidate"
  match "/edit_job_post/:id"                      => "job_posts#edit_job_post"
  put "/update_job_post"                          => "job_posts#update_job_post"
  delete "/delete_job_post/:id"                   => "job_posts#delete_job_post"
  match   "/profile/:id"                          => "job_posts#show_profile"
  match "update_profile"                            => "job_posts#update_profile"

  resources :job_posts, :only =>[:update], :as    => :recruiter_path

  match "/candidate_details/:type/:id" => 'job_posts#candidate_details'

  match "/create/job" => "job_posts#create_job", :as => :create_job
  match 'my_post' => 'job_posts#my_post'
  match "/jobs" => "job_posts#show_jobs", :as => :show_jobs #posted by recruiters
  match "/all_jobs" => "job_seekers#all_jobs", :as => :all_jobs
  match "/job_detail/:id" => "job_seekers#job_description"
  match "/apply_for_job/:id" => "job_seekers#apply_for_job", :as => :apply_for_job
  match "/upload" => "job_seekers#upload_file"
  match "/apply_without_signup/:id" => "job_seekers#apply_without_signup", :as => :apply_without_signup
  match "/create_unregistered_user" => "job_seekers#create_unregistered_user", :as => :create_user_record
  match "/signup/second_step/:id" => "job_seekers#signup_second_step", :as => :signup_second_step
  match "/creating_user_info" => "job_seekers#creating_user_info", :as => :creating_user_info
  match "/update_states" => "job_seekers#update_states"
  match "/jobseeker/dashboard" => "job_seekers#jobseeker_dashboard", :as => :jobseeker_dashboard

  root :to => 'home#index'

end

app/models/job_post.rb
class JobPost < ActiveRecord::Base

  attr_accessible :job_title, :position, :country_id, :state_id, :city, :zip_code, :salary,
    :term_of_assignment, :length, :job_description, :recruiter_id, :job_post_and_skills

  belongs_to :recruiter

  # belongs_to :job_post

  belongs_to :country
  
  belongs_to :state
  has_many :job_post_and_skills, :dependent => :destroy


  # has_and_belongs_to_many :skills
  accepts_nested_attributes_for :job_post_and_skills#, :reject_if => lambda { |a| a.values.all?(&:blank?) }
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController

  layout "recruiter"
  def job_post
    @job_post = JobPost.new
    @job_post.job_post_and_skills.new
  end

  def create_job

    @job_post = current_recruiter.job_posts.new(params[:job_post])
    #    p 'ssssssssssssssssssssssss'
    #    p current_recruiter.id
    #    exit
    if @job_post.save!
      parameters = params[:job_post][:job_post_and_skills_attributes]
      parameters.each do |f|
        @job_post.job_post_and_skills.create(:skill_id =>f[1][:id])
      end

      flash[:notice] = "User successfully created"
      redirect_to show_jobs_path
    else
      redirect_to :back
    end
  end

  def show_jobs
    @id = current_recruiter.id
    @jobs = JobPost.find_all_by_recruiter_id(@id)
  end

  # Recruitor's accessibility action
  def my_post
    @recruitor = current_recruiter
    @all_post = @recruitor.job_posts
  end

  def edit_job_post

    @job_post = JobPost.where(:recruiter_id=>current_recruiter.id,:id=>params[:id]).first
  end

  def update_job_post

    @job_post = JobPost.where(:recruiter_id=>current_recruiter.id,:id=>params[:id]).first
    if @job_post.update_attributes(params[:job_post])
      redirect_to my_post_path
      flash[:notice] = "Job Post successfully updated!"
    else
      flash[:notice] = "Please try again"
      redirect_to :back
    end
  end

  def delete_job_post

    @job_post = JobPost.where(:recruiter_id=>current_recruiter.id,:id=>params[:id]).first
    if @job_post.destroy
      flash[:notice] = "Successfully deleted Job Post!"
      redirect_to my_post_path
    else
      flash[:notice]= "Please try again!"
      redirect_to :back
    end
  end

  def show_applied_candidate
    # List of candidate who have applied to a job
    list = JobPost.where(:recruiter_id=>current_recruiter.id,:id=>params[:id])
    if not list.empty?
      @candidate_list = JobPortal.candidate_list(list.first)
    else
      flash[:notice] = "Access permission is not allowed"
      redirect_to :my_post
    end
  end

  def candidate_details
    if params[:type].eql?('user')
      @candidate = User.find params[:id]
      @file = file =Rails.root.join('public'+ @candidate.attached_files.last.dumpfile.to_s)
      file = file.to_s.split('?')[0]

      @filename = @candidate.attached_files.last.dumpfile

    else
      @candidate = UnregisteredUser.find params[:id]

      @filename = @candidate.attached_files.last.dumpfile_file_name
      @type = @candidate.attached_files.last.dumpfile_content_type

    end
  end

  # Recruiter's Profile
  def show_profile
    @recruiter = Recruiter.find params[:id]

    respond_to do |format|
      format.html
    end
  end

  def update_profile
    p params[:recruiter][:email].blank?
    p params[:recruiter][:email].empty?
    p "================="
    if params[:id].eql?(current_recruiter.id.to_s)
      @recruiter = Recruiter.find params[:id]
      if @recruiter.update_attributes(params[:recruiter])
        flash[:notice] = "Your Profile updated successfully!"
        redirect_to rec_index_path
      else
        flash[:notice] = " #{@recruiter.errors.full_messages.join(', ')}"
        redirect_to :back
      end
    else
      flash[:notice] = "Unauthorized access!"
      redirect_to :back
    end
  end

end

app/views/job_posts/_fieldsjobposts.html.erb
<div class="field">
	<%= f.label :job_title %>
	<br />
	<%= f.text_field :job_title %>
</div>
<div class="field">
	<%= f.label :position %>
	<br />
	<%= f.text_field :position %>
</div>
<div class="field">
	<%= f.label :country %>
	<br />
	
	<%#= f.text_field :country %>
</div>
<div class="field">
	<%= f.label :state %>
	<br />
	<%#= f.text_field :state %>
</div>
<div class="field">
	<%= f.label :city %>
	<br />
	<%= f.text_field :city %>
</div>
<%#*
<div class="field">
	%>
	<%#= f.label :start_date %>
	<%#= f.date_select :start_date %>
	<%#*
</div>
%>
<div class="field">
	<%= f.label :zip_code %>
	<br />
	<%= f.text_field :zip_code %>
</div>
<div class="field">
	<%= f.label :salary %>
	<br />
	<%= f.text_field :salary %>
</div>
<div class="field">
	<%= f.label :term_of_assignment %>
	<br />
	<%= f.text_field :term_of_assignment %>
</div>
<div class="field">
	<%= f.label :length %>
	<br />
	<%= f.text_field :length %>
</div>
<div class="field">
	<%= f.label :job_description %>
	<br />
	<%= f.text_field :job_description %>
</div>
<div class="field">
	<%= f.fields_for :job_post_and_skills do |skill| %>
	<%= skill.label :skill_name %>
	<br/>
	<%= skill.collection_select(:id, Skill.all,:id,:name, :prompt => "Please select skill") %>
	<%#= skill.text_field :name %>
	<% end %>
</div>

app/views/job_posts/_profile.html.erb
<%= form_for @recruiter, :url=>update_profile_path(:id=>@recruiter) do |recruiter| %>
<div class="userBox">
	<div class="profileSection">
		<div class="ciruserBg">
			<img src="/assets/user.png" alt="user" title="user" class="grUser" />
		</div>
		<ul>
			<li>
				<ul class="ul" style="margin-bottom:-10px; float:left;">
					<li>
						<label for="upload">Picture</label>
						<input type="file" id="inpF"  name="inpF" />
					</li>
				</ul>
			</li>
			<li>
				<label>First Name</label>
				<div class="leftGreyBg">
					<%= recruiter.text_field :first_name,:placeholder =>"First Name" %>
					<!-- <input type="text" name="First Name" onclick="if(this.value=='First Name'){this.value=''}" onblur="if(this.value==''){this.value='First Name'}" /> -->
				</div>
			</li>
			<li>
				<label>Last Name</label>
				<div class="leftGreyBg">
					<%= recruiter.text_field :last_name,:placeholder=>"Last Name" %>
					<!-- <input type="text" name="Last Name" onclick="if(this.value=='Last Name'){this.value=''}" onblur="if(this.value==''){this.value='Last Name'}" /> -->
				</div>
			</li>
			<li>
				<label>Postition Title</label>
				<div class="leftGreyBg">
					<%= recruiter.text_field :position_title,:placeholder=>"Position Title" %>
					<!-- <input type="text" name="Postition Title" onclick="if(this.value=='Postition Title'){this.value=''}" onblur="if(this.value==''){this.value='Postition Title'}" /> -->
				</div>
			</li>
			<li>
				<label>Email Address</label>
				<div class="leftGreyBg">
					<%= recruiter.text_field :email,:placeholder=>"Email Address" %>
					<!-- <input type="text" name="Email Address" onclick="if(this.value=='Email Address'){this.value=''}" onblur="if(this.value==''){this.value='Email Address'}" /> -->
				</div>
			</li>
			<li>
				<label>Phone Number</label>
				<div class="leftGreyBg">
					<%= recruiter.text_field :phone_number,:placeholder=>"Phone Number" %>
					<!-- <input type="text" name="Phone Number" onclick="if(this.value=='Phone Number'){this.value=''}" onblur="if(this.value==''){this.value='Phone Number'}" /> -->
				</div>
			</li>
		</ul>
	</div>
	<ul class="socialIcon leftMargin">
		<li>
			<a href="#" title="Facebook"><img src="/assets/facebook-button.png" alt="Facebook" /></a>
		</li>
		<li>
			<a href="#" title="Twitter"><img src="/assets/twitter-button.png" alt="Twitter" /></a>
		</li>
		<li>
			<a href="#" title="LinkedIn"><img src="/assets/linkedin-button.png" alt="LinkedIn" /></a>
		</li>
	</ul>
</div>
<div class="marCent cl">
	<div class="subBtn fl">
		<%= recruiter.submit "Submit", :class=> "signText" %>
		<!-- <input type="button" value="Submit" class="signText" /> -->
	</div>
	<div class="cancelBtn fl">
		<input type="button" value="Cancel" class="signText" />
	</div>
</div>

<% end %>

app/views/job_posts/candidate_details.html.erb
<p>
	Candidate Details
</p>
<!-- This is to displya the resume file of candidate -->
<iframe src="http://docs.google.com/viewer?url=http://blog.unsri.ac.id/userfiles/26156855-Cloud-Computing.doc&embedded=true" width="600" height="580" style="border: none;"></iframe>

app/views/job_posts/edit_job_post.html.erb
<%= form_for @job_post, :url => update_job_post_path(:id=>@job_post) do |f| %>
<%= render :partial =>"fieldsjobposts", :locals => {:f => f} %>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/job_posts/job_post.html.erb
<%= form_for @job_post, :url => create_job_path(@job_post) do |f| %>
<%= render :partial =>"fieldsjobposts", :locals =>{:f => f} %>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/job_posts/my_post.html.erb
<p>
	List of posted Jobs
</p>
<% @all_post.each do |f| %>
<% if not f.job_title.eql?('') %>
<p>
	<%= f.job_title %> | <%= f.position %> | <%= link_to 'Candidates Applied', "/candidates/#{f.id}" %> <%= link_to "Edit", "/edit_job_post/#{f.id}" %>
	<%= link_to "Remove", "/delete_job_post/#{f.id}", :confirm =>"Are you sure", :method=>:delete %>
	<% jobpath = root_url.to_s + "job_detail/#{f.id}" %>
	<%= render :partial => "share/social_script", :locals => {:jobpath => jobpath} %>
</p>
<% end %>
<% end %>

app/views/job_posts/show_applied_candidate.html.erb
<h1> Candidate List</h1>

<% @candidate_list.each do |list| %>

<p>
	<%= list.email %> <%= link_to "More", "/candidate_details/#{list.class.to_s.downcase}/#{list.id}" %>
</p>

<% end%>

app/views/job_posts/show_jobs.html.erb
<% @jobs.each do |f| %>
  <%= link_to f.job_title, "#" %>&nbsp;at&nbsp;
  <%= link_to f.city, "#" %><br />
<% end %>

app/views/job_posts/show_profile.html.erb
<div class="contentBg">
	<div class="container">
		<div class="content">
			<div class="contentSection">
				<h3>Profile Settings</h3>
				<div class="upArrow"></div>
				<div class="profileSetIcon"></div>
			</div>
			<%= render :partial =>"profile", :locals => {:recruiter => @recruiter} %>
		</div>
	</div>
</div>