config/routes.rb
Getlive::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :recruiters do |f|
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "registrations#new"
  end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" } do |f|
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    match "/creating_jobseeker" => "registrations#creating_jobseeker", :as => :creating_jobseeker
  end

  match "/auth/:provider/callback" => "authorizations#create"

  match "/list_of_applied"                        => "job_posts#show_applied_candidate"
  match "/recruiter/home"                         => "home#rec_index", :as => :rec_index
  match "/search/resume"                          => "home#search_resume", :as => :search_resume
  match "/aboutus"                                => "home#about_us", :as => :about_us
  match "/post/job"                               => "job_posts#job_post", :as => :job_post
  match "/candidates/:id"                         => "job_posts#show_applied_candidate"
  match "/edit_job_post/:id"                      => "job_posts#edit_job_post"
  put "/update_job_post"                          => "job_posts#update_job_post"
  delete "/delete_job_post/:id"                   => "job_posts#delete_job_post"
  match   "/profile/:id"                          => "job_posts#show_profile"
  match "update_profile"                            => "job_posts#update_profile"

  resources :job_posts, :only =>[:update], :as    => :recruiter_path

  match "/candidate_details/:type/:id" => 'job_posts#candidate_details'

  match "/create/job" => "job_posts#create_job", :as => :create_job
  match 'my_post' => 'job_posts#my_post'
  match "/jobs" => "job_posts#show_jobs", :as => :show_jobs #posted by recruiters
  match "/all_jobs" => "job_seekers#all_jobs", :as => :all_jobs
  match "/job_detail/:id" => "job_seekers#job_description"
  match "/apply_for_job/:id" => "job_seekers#apply_for_job", :as => :apply_for_job
  match "/upload" => "job_seekers#upload_file"
  match "/apply_without_signup/:id" => "job_seekers#apply_without_signup", :as => :apply_without_signup
  match "/create_unregistered_user" => "job_seekers#create_unregistered_user", :as => :create_user_record
  match "/signup/second_step/:id" => "job_seekers#signup_second_step", :as => :signup_second_step
  match "/creating_user_info" => "job_seekers#creating_user_info", :as => :creating_user_info
  match "/update_states" => "job_seekers#update_states"
  match "/jobseeker/dashboard" => "job_seekers#jobseeker_dashboard", :as => :jobseeker_dashboard

  root :to => 'home#index'

end

app/views/layouts/_flashmsgbox.html.erb
<% if !flash[:notice].nil? or !flash[:error].nil? or !flash[:alert].nil? or !flash[:info].nil? %>
  <div class="message_box" id="msgbox">
    <div class="message_left">
      <%#=image_tag("/assets/message_left1.png")%>
    </div>
    <div class="message_middle">
      <%#=image_tag("/assets/message_icon1.png")%>
      <p>
        <% if not flash[:info].nil? %>
          <%= flash[:info] %>
        <% else %>
          <%= flash[:notice] %><%= flash[:error] %> <%= flash[:alert] %>
        <% end %>
      </p>
    </div>
    <div class="message_right">
      <a id="hidemsg" style="cursor:pointer;"><%#=image_tag("/assets/close_i.png")%></a>
    </div>
  </div>
<% end %>

<div class="clear"></div>

<script type="text/javascript">
  $(function() {
    $('a#hidemsg').click(function () {
      $('#msgbox').hide();

    });
    $('.message_box').delay(5000).fadeOut();
  });
</script>

app/views/layouts/_footer.html.erb
<div class="cl"></div>
<div id="mainfooter">
	<div class="footer">
		<div class="copyRight">
			&copy; Copyright 2013 Get Live. All rights reserved.
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<% if current_recruiter %>
  <%= link_to "sign out", destroy_recruiter_session_path, :method => :delete %><br />
<% elsif current_user %>
  <%= link_to "Hey #{current_user.email}", destroy_user_session_path, :method => :delete %> |
  <%= link_to "sign out", destroy_user_session_path, :method => :delete %><br />
<% else %>
  <div class="rec_left">
    <%= link_to "signin as recruiter", new_recruiter_session_path %><br />
    <%= link_to "signin as user", new_user_session_path %><br />
  </div>
  <div class="rec_right">
    <%= link_to "signup as user", new_user_registration_path %><br />
    <%= link_to "Browse Jobs", all_jobs_path %><br />
  </div>
<% end %>

app/views/layouts/_header_scripts.html.erb
<script type="text/javascript" language="javascript">
	var d = document;
	var safari = (navigator.userAgent.toLowerCase().indexOf('safari') != -1) ? true : false;
	var gebtn = function(parEl, child) {
		return parEl.getElementsByTagName(child);
	};
	onload = function() {

		var body = gebtn(d,'body')[0];
		body.className = body.className && body.className != '' ? body.className + ' has-js' : 'has-js';

		if (!d.getElementById || !d.createTextNode)
			return;
		var ls = gebtn(d, 'label');
		for (var i = 0; i < ls.length; i++) {
			var l = ls[i];
			if (l.className.indexOf('label_') == -1)
				continue;
			var inp = gebtn(l,'input')[0];
			if (l.className == 'label_check') {
				l.className = (safari && inp.checked == true || inp.checked) ? 'label_check c_on' : 'label_check c_off';
				l.onclick = check_it;
			};
			if (l.className == 'label_radio') {
				l.className = (safari && inp.checked == true || inp.checked) ? 'label_radio r_on' : 'label_radio r_off';
				l.onclick = turn_radio;
			};
		};
	};
	var check_it = function() {
		var inp = gebtn(this,'input')[0];
		if (this.className == 'label_check c_off' || (!safari && inp.checked)) {
			this.className = 'label_check c_on';
			if (safari)
				inp.click();
		} else {
			this.className = 'label_check c_off';
			if (safari)
				inp.click();
		};
	};
	var turn_radio = function() {
		var inp = gebtn(this,'input')[0];
		if (this.className == 'label_radio r_off' || inp.checked) {
			var ls = gebtn(this.parentNode, 'label');
			for (var i = 0; i < ls.length; i++) {
				var l = ls[i];
				if (l.className.indexOf('label_radio') == -1)
					continue;
				l.className = 'label_radio r_off';
			};
			this.className = 'label_radio r_on';
			if (safari)
				inp.click();
		} else {
			this.className = 'label_radio r_off';
			if (safari)
				inp.click();
		};
	}; 
</script>

app/views/layouts/_rec_header.html.erb
<div id="header">
	<div class="headerSection">
		<h1 id="slogo"><a href="recruiter-signin.html" title="GLC - Get Live Consulting Inc">GLC - Get Live Consulting Inc</a></h1>
		<div id="menu_wrapper" class="blue">
			<div class="left"></div>
			<ul id="menu">

				<% if params[:action].eql?('rec_index')  %>
				<li class="active">
					<% else %>
				<li>
					<% end %>
					<%= link_to "Dashboard", rec_index_path %>
					<!-- <a href="#">Dashboard</a> -->
				</li>
				<% if params[:action].eql?('job_post')%>
				<li class="active">
					<% else %>
				<li>
					<% end %>

					<%= link_to "Post Jobs", job_post_path %>
					<!-- <a href="#">Post Jobs</a> -->
				</li>
				<% if params[:action].eql?('my_post') %>
				<li class="active">
					<% else %>
				<li>
					<% end %>
					<%= link_to "Manage Jobs", my_post_path %>
					<!-- <a href="#">Manage Jobs</a> -->
				</li>

				<% if params[:action].eql?('search_resume') %>
				<li class="active">
					<% else %>
				<li>
					<% end %>
					<%= link_to "Seach Resume", search_resume_path %>
					<!-- <a href="#">Search Resume</a> -->
				</li>
				
				<% if params[:action].eql?('show_profile ') %>
				<li classclass="active">
					<% else %>
				<li>
					<% end %>
					<%= link_to "Profile Settings","/profile/#{current_recruiter.id}" %>
					<!-- <a href="#">Profile Settings</a> -->
				</li>
				<li>
					<%= link_to "Sign Out", destroy_recruiter_session_path, :method => :delete %>
					<!-- <a href="#">Sign Out</a> -->
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="cl"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>GLC - Get Live Consulting Inc</title>
		<link href="css/style.css" rel="stylesheet" type="text/css" />
		<%= render "layouts/header_scripts" %>
		<%= stylesheet_link_tag    "application" %>
		<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
		<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>

	<body>
		<div id="dashboard">
			<%= render :partial =>"layouts/flashmsgbox" %>
		</div>
		<div id="wrapper" class="topHeader">

			<div class="centerBg">
				<%= yield %>
			</div>
		</div>
		<%= render "layouts/footer" %>
	</body>

	<!-- <body>
	<div id="wrapper" class="topHeader">
	<div class="centerBg">
	<div id="header">
	<h1 id="logo"><a href="recruiter-signin.html" title="GLC - Get Live Consulting Inc">GLC - Get Live Consulting Inc</a></h1>
	<h2 class="mainText">Get Live Recruitment Center</h2>
	</div>
	<div class="container">
	<ul class="signInBox">
	<li>
	<input type="text" class="inputText" name="Username" value="Username" onclick="if(this.value=='Username'){this.value=''}" onblur="if(this.value==''){this.value='Username'}" />
	</li>
	<li>
	<input type="text" class="inputText" name="Password" value="Password" onclick="if(this.value=='Password'){this.value=''}" onblur="if(this.value==''){this.value='Password'}" />
	</li>
	<li>
	<div class="signInBtn">
	<input type="button" class="signText" value="Sign In" name="Sign In" />
	</div>
	</li>
	<div>
	<label class="label_check" for="sample-check">
	<input name="sample-check" id="sample-check" value="1" type="checkbox" />
	Remember me </label>

	</div>
	<div>
	<a href="#" title="Forgot your password?" class="pwLink">Forgot your password?</a>
	</div>
	</ul>
	</div>
	<div class="cl"></div>
	<div id="mainfooter">
	<div class="footer">
	<div class="copyRight">
	&copy; Copyright 2013 Get Live. All rights reserved.
	</div>
	</div>
	</div>
	</div>
	</div>

	</body> -->
</html>

app/views/layouts/recruiter.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>GLC - Get Live Consulting Inc</title>
		<link href="css/style.css" rel="stylesheet" type="text/css" />
		<%= render "layouts/header_scripts" %>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<!-- <script type="text/javascript">
		$(document).ready(function() {
		$('.ul').jqf1();
		});
		</script> -->
	</head>

	<body>
		<div id="wrapper" class="intopHeader">
			<div id="dashboard">
				<%= render :partial =>"layouts/flashmsgbox" %>
			</div>
			<%= render :partial=> "layouts/rec_header" %>
			<%= yield %>

			<%= render "layouts/footer" %>
		</div>

	</body>
</html>